spring:
    kafka:
        bootstrap-servers: localhost:29092, localhost:29093, localhost:29094
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
            properties:
                spring.json.type.mapping: paymentToken:com.srikant.kafka.paymentgenerator.model.PaymentEvent #in the message header there will be paymentToken
                acks: all
                retries: 5

    application:
        name: payment-generator
server:
    port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
