server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: fraud-detector-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.srikant.kafka.paymentgenerator.model.PaymentEvent:com.srikant.frauddetector.model.PaymentEvent
        spring.json.value.default.type: com.srikant.frauddetector.model.PaymentEvent

    application:
        name: fraud-detector