server:
  port: 0 #random port

spring:
  application:
    name: spring-kafka-avro-demo
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:28081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer


    consumer:
      group-id: avro-consumer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        