server:
    port: 8083

spring:
    application:
        name: alertservice
    kafka:
        bootstrap-servers: localhost:29092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
            properties:
                spring.json.add.type.headers: true
        consumer:
            group-id: alert-service-group
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
                spring.json.value.default.type: com.srikant.alertservice.model.FraudAlert

management:
    endpoints:
        web:
            exposure:
                include: health,prometheus

    endpoint:
        health:
            show-details: always

    prometheus:
        metrics:
            export:
                enabled: true
