server:
  port: 0 #random port

spring:
  application:
    name: spring-kafka-manual-ack-demo
  kafka:
    bootstrap-servers: "localhost:29092, localhost:29093, localhost:29094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        request.timeout.ms: 5000
        delivery.timeout.ms: 120000
        retry.backoff.ms: 100           # Wait 5 seconds between retries
        retry.backoff.max.ms: 3000   # Max backoff cap
                  # Small batch window